[[Auth-API]]
= *Auth API*

[[회원가입-API]]
== *1. 회원가입-API*

==== *1-1* 프로필 X

operation::auth-controller-test/given-all-info_then-success[snippets='http-request,request-parameters,response-body']

==== *1-2* 프로필 O

operation::auth-controller-test/given-all-info_when-profile-exists_then-success[snippets='http-request,request-parts,response-body']

==== *1-3* 이메일, 비밀번호 Validation 에러

operation::auth-controller-test/given-wrong-email-and-nickname_then-fail[snippets='http-request,request-parameters,response-body']

[[로그인-API]]
== *2. 로그인-API*

==== *2-1* 성공

operation::auth-controller-test/given-all-info_when-sign-in_then-success[snippets='http-request,request-body,response-body,response-headers']

==== *2-2* 존재하지 않는 유저

operation::auth-controller-test/given-not-exist-info_when-sign-in_then-fail[snippets='http-request,request-body,response-body']

==== *2-3* 비밀번호 오류

operation::auth-controller-test/given-wrong-info_when-sign-in_then-fail[snippets='http-request,request-body,response-body']

[[이메일-중복-확인-API]]
== *3. 이메일 중복 확인 API*

==== *3-1* 이메일 중복 X

operation::auth-controller-test/given-not-duplicated-email_then-success[snippets='http-request,request-body,request-fields,response-body,response-fields']

==== *3-2* 이메일 중복 O

operation::auth-controller-test/given-duplicated-email_then-fail[snippets='http-request,request-body,request-fields,response-body,response-fields']

==== *3-3* 이메일 값 NULL

operation::auth-controller-test/given-null-email_then-fail[snippets='http-request,request-body,request-fields,response-body,response-fields']

[[닉네임-중복-확인-API]]
== *4. 닉네임 중복 확인 API*

==== *4-1* 닉네임 중복 X

operation::auth-controller-test/given-duplicated-nickname_then-fail[snippets='http-request,request-body,request-fields,response-body,response-fields']

==== *4-2* 닉네임 중복 O

operation::auth-controller-test/given-not-duplicated-nickname_then-success[snippets='http-request,request-body,request-fields,response-body,response-fields']

==== *4-3* 닉네임 값 NULL

operation::auth-controller-test/given-null-nickname_then-fail[snippets='http-request,request-body,request-fields,response-body,response-fields']